### ISSUE TITLE
Site is not working?

### ISSUE THREAD

**Issue by danzen** [circlecell/jscompress.com#40]
Hey folks - I have been using the https://jscompress.com/ site for a while - thanks!  Today, the tool does not seem to work - it tells me 100% compression - even on files I have compressed successfully before.  Also... does it look different?  You used to have the ES6 compression checkbox on the top right and that is gone.  Here's hoping it was just a bad update or something...

**Comment by opajaap** [comment]
The comments are not removed anymore???

**Comment by finom** [comment]
@danzen can you provide the problematic code?

> does it look different?

We used UglifyJS as a default library for compression and babili (now called babel-minify) as an optional but unstable minifier for ECMAScript 2015+. Today babel-minify is quite stable so we've decided to completely kill UglifyJS and use babel-minify by default.  

@opajaap fixed, thank you.

**Comment by laukstein** [comment]
@finom I can confirm that "Compress JavaScript" no longer is works on large JavaScript entries, it empties whole pasted JavaScript, throws some exceptions on Console:

![grabilla g11508](https://user-images.githubusercontent.com/183966/52583352-0e089300-2e38-11e9-9d81-e0b143cc997b.png)

You can reproduce the issue trying to paste and compress https://browser.sentry-cdn.com/4.5.4/bundle.js 

Maybe is caused by https://github.com/circlecell/jscompress.com/commit/92a3de5bf26a6bbe644d758ced8de6e108335c4c

**Comment by danzen** [comment]
This is what I was compressing... been doing files this size for the last few years without a problem - including a week or so ago... https://d309knd7es5f10.cloudfront.net/zim_10_doc.js

**Comment by finom** [comment]
@laukstein @danzen thank you guys, It's caused by https://github.com/babel/minify/issues/904 
Temporary disabling https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-builtins :(

**Comment by finom** [comment]
The option will be enabled as soon as they fix the bug.

**Comment by danzen** [comment]
I was able to compress... the Firefox browser did warn 3 times that it was being slowed down and do I want to cancel the script - I think it has done that in the past on occasion - but I think it was only once not three times.  Anyway - it managed - thank you.

**Comment by finom** [comment]
Guys, I've brought back UglifyJS because it seems like babel-minify isn't as good as we would expect.
